# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7f09ff014ea75b0c894cf0cdea3be12105326a28138bb3ef59ac25795b0bafa8ffbc0fcdb7a8e69b0bfb77481901c7a6b8fd02315b29667900e1e06296b7a9fb

test:
  secret_key_base: 89790de8a62e8ca37fe8892a6d60d5b2f8e88f5196cb65bc426c278bd012b2193513d3ffd359d776e1203b882889ac0656264ebb615ee4fd54fd86c8a7b5690c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
